#!/usr/bin/env ruby
# Generates actions/ from templates/actions/.
#
#   *.yml      -> copied as-is (with a generated header prepended)
#   *.yml.erb  -> rendered via ERB, inlining reusable steps from templates/steps/
#
# Reusable steps live in templates/steps/<name>.yml.erb and are pulled into an
# action (or another step) with `<%= render_step('<name>', ...) %>`. Anything
# bespoke to a single action just stays inline in that action's template. To find
# the source of any actions/<path>/action.yml, look at templates/actions/<path>.yml(.erb).
# Edit templates/, never actions/.

require 'erb'
require 'fileutils'

module ActionGenerator
  REPO_ROOT     = File.expand_path('..', __dir__)
  TEMPLATES_DIR = File.join(REPO_ROOT, 'templates', 'actions')
  STEPS_DIR     = File.join(REPO_ROOT, 'templates', 'steps')
  OUTPUT_DIR    = File.join(REPO_ROOT, 'actions')

  GENERATED_HEADER = "# GENERATED by scripts/generate.rb — edit templates/, not this file.\n"

  # The rendering scope for a template. An instance's `binding` is handed to ERB,
  # so the ONLY methods a template (.yml.erb) can call are this class's PUBLIC
  # methods — currently just render_step. Internal helpers stay private.
  class Template
    def initialize(source)
      @source = source
    end

    # Renders the template. Keyword args are exposed to the template as a
    # `locals` hash (read with `locals.fetch(:name) { default }`).
    def render(**locals)
      ERB.new(@source, trim_mode: '-').result(binding)
    end

    # Inlines a reusable step (templates/steps/<name>.yml.erb) under a `steps:`
    # key. The fragment may hold several steps and may compose other steps.
    # Keyword args reach the step as `locals` (read with locals.fetch(:x) { default }).
    #
    # `if:` is the composing action's one control-flow knob. GitHub has no way to
    # guard a group of steps in a flat composite action, so when `on-failure`
    # flattens into several sibling steps, the single `if: failure()` written at
    # the call site is stamped onto EACH of them. Everything else a step
    # decides — slack configured? dry run? — is a shell self-guard (`exit 0`),
    # never an `if:`, so there is never a condition to merge. Omit `if:` to run
    # unconditionally.
    def render_step(name, indent: 4, **locals)
      step = Template.new(File.read(File.join(STEPS_DIR, "#{name}.yml.erb"))).render(**locals)
      step = with_if(step, locals[:if]) if locals.key?(:if)
      indent_lines(step, indent)
    end

    private

    # Stamps `if: <condition>` as the first key of every top-level step in a
    # fragment. Steps carry no `if:` of their own (they self-guard in shell), so
    # there is nothing to collide with.
    def with_if(fragment, condition)
      return fragment if condition.nil? || condition.empty?
      fragment.split(/^(?=- )/).map do |step|
        next step unless step.start_with?('- ')
        head, rest = step.split("\n", 2)
        keys_indent = head[/^\s*-\s*/].tr('-', ' ')   # align the new key with the step's other keys
        "#{head}\n#{keys_indent}if: #{condition}\n#{rest}"
      end.join
    end

    def indent_lines(text, indent)
      pad = ' ' * indent
      text.lines.map { |line| line.strip.empty? ? line : pad + line }.join.rstrip
    end
  end

  # ── Orchestration (not reachable from templates) ──────────────────────────
  module_function

  def run
    FileUtils.rm_rf(OUTPUT_DIR)   # regenerate clean so deletions in templates/ propagate
    template_paths.each { |path| generate(path) }
    puts "Done."
  end

  def template_paths
    Dir.glob("#{TEMPLATES_DIR}/**/*.{yml,yml.erb}").sort
  end

  def generate(template_path)
    out_path = output_path_for(template_path)
    FileUtils.mkdir_p(File.dirname(out_path))
    File.write(out_path, GENERATED_HEADER + render_action(template_path))
    puts "  #{erb?(template_path) ? 'rendered' : 'copied '} → #{out_path.sub("#{REPO_ROOT}/", '')}"
  end

  def render_action(template_path)
    source = File.read(template_path)
    erb?(template_path) ? Template.new(source).render : source
  end

  def erb?(path)
    path.end_with?('.erb')
  end

  # templates/actions/release/notify-pending.yml.erb -> actions/release/notify-pending/action.yml
  def output_path_for(template_path)
    relative = template_path.sub("#{TEMPLATES_DIR}/", '').sub(/\.erb$/, '')
    action   = relative.delete_suffix('.yml')
    File.join(OUTPUT_DIR, action, 'action.yml')
  end
end

ActionGenerator.run
