#!/usr/bin/env ruby
# Generates actions/ from templates/actions/.
#
#   *.yml      -> copied as-is (with a generated header prepended)
#   *.yml.erb  -> rendered via ERB, inlining reusable steps from templates/steps/
#
# Reusable steps live in templates/steps/<name>.yml.erb and are pulled into an
# action (or another step) with `<%= render_step('<name>', ...) %>`. Anything
# bespoke to a single action just stays inline in that action's template. To find
# the source of any actions/<path>/action.yml, look at templates/actions/<path>.yml(.erb).
# Edit templates/, never actions/.

require 'fileutils'
require_relative 'lib/template'

module ActionGenerator
  REPO_ROOT     = File.expand_path('..', __dir__)
  TEMPLATES_DIR = File.join(REPO_ROOT, 'templates', 'actions')
  STEPS_DIR     = File.join(REPO_ROOT, 'templates', 'steps')
  OUTPUT_DIR    = File.join(REPO_ROOT, 'actions')

  GENERATED_HEADER = "# GENERATED by scripts/generate.rb — edit templates/, not this file.\n"

  # Soft-semver, scoped per action FAMILY (the top dir under templates/actions/, e.g.
  # `release`). The version lives in that family's VERSION file and is stamped into every
  # action it generates. Consumers pin our actions by SHA — this number is NOT a git tag;
  # it's a risk signal for diffing two pinned SHAs: a major jump = breaking change (inputs
  # removed/renamed, behavior contract changed), minor = additive, patch = fix. Scoped per
  # family so one family's breaking change never forces a major bump on the others.

  # The ERB engine (Template#render / #render_step) lives in scripts/lib/template.rb,
  # shared with bin/workflow. Actions render through Templating::Template with the
  # composite-action steps root (STEPS_DIR); see render_action below.

  # ── Orchestration (not reachable from templates) ──────────────────────────
  module_function

  def run
    FileUtils.rm_rf(OUTPUT_DIR)   # regenerate clean so deletions in templates/ propagate
    template_paths.each { |path| generate(path) }
    puts "Done."
  end

  def template_paths
    Dir.glob("#{TEMPLATES_DIR}/**/*.{yml,yml.erb}").sort
  end

  def generate(template_path)
    out_path = output_path_for(template_path)
    FileUtils.mkdir_p(File.dirname(out_path))
    File.write(out_path, header_for(template_path) + render_action(template_path))
    puts "  #{erb?(template_path) ? 'rendered' : 'copied '} → #{out_path.sub("#{REPO_ROOT}/", '')}"
  end

  # The generated header plus, when the action belongs to a versioned family, a
  # machine-parseable JSON metadata comment stamped from that family's VERSION file:
  #   # sdk-actions: {"family":"release","version":"1.0.0"}
  # (a comment, not a YAML key — action.yml has no native version field, and this
  # survives regeneration + can't trip the action schema).
  def header_for(template_path)
    family, version = family_version(template_path)
    return GENERATED_HEADER unless version
    GENERATED_HEADER + Templating.metadata_comment('family' => family, 'version' => version)
  end

  # Nearest VERSION file walking up from the template toward templates/actions/.
  # Returns [family, version] (family = that dir relative to templates/actions/,
  # e.g. "release"), or nil when no ancestor carries a VERSION.
  def family_version(template_path)
    dir = File.dirname(template_path)
    while dir.start_with?(TEMPLATES_DIR)
      version_file = File.join(dir, 'VERSION')
      return [dir.sub("#{TEMPLATES_DIR}/", ''), File.read(version_file).strip] if File.exist?(version_file)
      break if dir == TEMPLATES_DIR
      dir = File.dirname(dir)
    end
    nil
  end

  def render_action(template_path)
    source = File.read(template_path)
    erb?(template_path) ? Templating::Template.new(source, steps_dir: STEPS_DIR).render : source
  end

  def erb?(path)
    path.end_with?('.erb')
  end

  # templates/actions/release/notify-pending.yml.erb -> actions/release/notify-pending/action.yml
  def output_path_for(template_path)
    relative = template_path.sub("#{TEMPLATES_DIR}/", '').sub(/\.erb$/, '')
    action   = relative.delete_suffix('.yml')
    File.join(OUTPUT_DIR, action, 'action.yml')
  end
end

ActionGenerator.run
